name: $(date:yyyyMMdd)$(rev:-rr)

resources:
  repositories:
    - repository: templates
      endpoint: SuperJMN
      type: github
      name: SuperJMN/BuildTemplates
      ref: refs/tags/v2.5.0

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  PublishFramework: 'net7.0'
  PublishProject: 'Zafiro.Avalonia'
  PublishRuntime: ''
  Workloads: 'wasm-tools wasm-experimental android'

jobs:
  # - template: Test-PowerShell.yml@templates
  #   parameters:
  #     name: 'Test_Windows'
  #     vmImage: 'windows-2022'
  #     BuildConfiguration: ${{ variables.BuildConfiguration }}
  #     Workloads: ${{ variables.Workloads }} ios

  # - template: Test-Bash.yml@templates
  #   parameters:
  #     name: 'Test_Linux'
  #     vmImage: 'ubuntu-20.04'
  #     BuildConfiguration: ${{ variables.BuildConfiguration }}
  #     Workloads: ${{ variables.Workloads }}

  # - template: Test-Bash.yml@templates
  #   parameters:
  #     name: 'Test_macOS'
  #     vmImage: 'macOS-12'
  #     BuildConfiguration: ${{ variables.BuildConfiguration }}
  #     Workloads: ${{ variables.Workloads }} ios

  # - template: Pack-MyGet.yml@templates
  #   parameters:
  #     name: 'Pack_MyGet'
  #     vmImage: 'windows-2022'
  #     BuildConfiguration: ${{ variables.BuildConfiguration }}
  #     Workloads: ${{ variables.Workloads }} ios

  - template: Pack-NuGet.yml@templates
    parameters:
      name: 'Pack_NuGet'
      vmImage: 'windows-2022'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      Workloads: ${{ variables.Workloads }} ios

  # - template: Publish-PowerShell.yml@templates
  #   parameters:
  #     name: 'Publish_Windows_x64'
  #     vmImage: 'windows-2022'
  #     BuildConfiguration: ${{ variables.BuildConfiguration }}
  #     Workloads: ${{ variables.Workloads }} ios
  #     PublishFramework: ${{ variables.PublishFramework }}
  #     PublishProject: ${{ variables.PublishProject }}
  #     PublishRuntime: 'win7-x64'

  # - template: Publish-PowerShell.yml@templates
  #   parameters:
  #       name: 'Publish_Windows_arm64'
  #       vmImage: 'windows-2022'
  #       BuildConfiguration: ${{ variables.BuildConfiguration }}
  #       Workloads: ${{ variables.Workloads }} ios
  #       PublishFramework: ${{ variables.PublishFramework }}
  #       PublishProject: ${{ variables.PublishProject }}
  #       PublishRuntime: 'win10-arm64'

  # - template: Publish-Bash.yml@templates
  #   parameters:
  #     name: 'Publish_Ubuntu_x64'
  #     vmImage: 'ubuntu-20.04'
  #     BuildConfiguration: ${{ variables.BuildConfiguration }}
  #     Workloads: ${{ variables.Workloads }}
  #     PublishFramework: ${{ variables.PublishFramework }}
  #     PublishProject: ${{ variables.PublishProject }}
  #     PublishRuntime: 'ubuntu.14.04-x64'

  # - template: Publish-Bash.yml@templates
  #   parameters:
  #       name: 'Publish_Ubuntu_arm64'
  #       vmImage: 'ubuntu-20.04'
  #       BuildConfiguration: ${{ variables.BuildConfiguration }}
  #       Workloads: ${{ variables.Workloads }}
  #       PublishFramework: ${{ variables.PublishFramework }}
  #       PublishProject: ${{ variables.PublishProject }}
  #       PublishRuntime: 'ubuntu.16.04-arm64'

  # - template: Publish-Bash.yml@templates
  #   parameters:
  #     name: 'Publish_Debian_x64'
  #     vmImage: 'ubuntu-20.04'
  #     BuildConfiguration: ${{ variables.BuildConfiguration }}
  #     Workloads: ${{ variables.Workloads }}
  #     PublishFramework: ${{ variables.PublishFramework }}
  #     PublishProject: ${{ variables.PublishProject }}
  #     PublishRuntime: 'debian.8-x64'

  # - template: Publish-Bash.yml@templates
  #   parameters:
  #       name: 'Publish_Debian_arm64'
  #       vmImage: 'ubuntu-20.04'
  #       BuildConfiguration: ${{ variables.BuildConfiguration }}
  #       Workloads: ${{ variables.Workloads }}
  #       PublishFramework: ${{ variables.PublishFramework }}
  #       PublishProject: ${{ variables.PublishProject }}
  #       PublishRuntime: 'debian.8-arm64'

  # - template: Publish-Bash.yml@templates
  #   parameters:
  #     name: 'Publish_macOS_x64'
  #     vmImage: 'macOS-12'
  #     BuildConfiguration: ${{ variables.BuildConfiguration }}
  #     Workloads: ${{ variables.Workloads }} ios
  #     PublishFramework: ${{ variables.PublishFramework }}
  #     PublishProject: ${{ variables.PublishProject }}
  #     PublishRuntime: 'osx.10.12-x64'

  # - template: Publish-Bash.yml@templates
  #   parameters:
  #       name: 'Publish_macOS_arm64'
  #       vmImage: 'macOS-12'
  #       BuildConfiguration: ${{ variables.BuildConfiguration }}
  #       Workloads: ${{ variables.Workloads }} ios
  #       PublishFramework: ${{ variables.PublishFramework }}
  #       PublishProject: ${{ variables.PublishProject }}
  #       PublishRuntime: 'osx.11.0-arm64'

  # - template: Publish-Bash-Android.yml@templates
  #   parameters:
  #       name: 'Publish_Bash_Android'
  #       vmImage: 'macOS-12'
  #       BuildConfiguration: ${{ variables.BuildConfiguration }}
  #       Workloads: ${{ variables.Workloads }} ios
  #       PublishFramework: 'net7.0-android'
  #       PublishProject: 'SeaweedFS.Gui.Android'
  #       PublishRuntime: ''