trigger:
  branches:
    include: [ master ]
pr:
  branches:
    include: [ master, "*" ]

pool:
  vmImage: ubuntu-latest

variables:
  - group: api-keys
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: '1'

steps:
  # Checkout completo + submódulos
  - checkout: self
    submodules: true
    fetchDepth: 0
  
  # Install .NET 9 SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '9.0.x'  # or '9.0.100' for exact version
      displayName: 'Install .NET 9 SDK'
  
  # DotnetDeployer.Tool
  - pwsh: |
      dotnet tool install --global DotnetDeployer.Tool
      dotnetdeployer --version
    displayName: Install DotnetDeployer.Tool
  
  # Empaquetado + publicación NuGet + release GitHub (real en master, dry-run en el resto)
  - pwsh: |
      $branch   = '$(Build.SourceBranch)'
      $isMaster = $branch -eq 'refs/heads/master'
      Write-Host "Branch: $branch. Is master: $isMaster"
      
      if ($isMaster) {
        Write-Host 'Publishing NuGet packages'
        dotnetdeployer nuget --api-key '$(NuGetApiKey)'
        dotnetdeployer github pages --github-token '$(GitHubApiKey)' --repository SuperJMN-Zafiro.github.io --owner SuperJMN-Zafiro --prefix TestApp
      } else {
        Write-Host 'NuGet dry run (no push)'
        dotnetdeployer nuget --api-key '$(NuGetApiKey)' --no-push
      }
    
    displayName: Package, Publish and Release
