using Avalonia.Metadata;

[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Controls")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Converters")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Behaviors")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.ViewLocators")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Controls.Shell")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Controls.SlimDataGrid")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Controls.Navigation")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Controls.Panels")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Controls.Wizards.Slim")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Services")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.MarkupExtensions")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Drawing")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Navigation")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Storage")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.Mixins")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.DesignTime")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia")]
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "Zafiro.Avalonia.ViewLocators")]